apple_binary(
    name = "binary-osx",
    srcs = [ "main.cpp" ],
    deps = [
        "//vendor/luacppinterface:luacppinterface",
        "//vendor/irrlicht:irrlicht-osx",
        "//vendor/newton-dynamics:newton-dynamics",
    ],
    compiler_flags = [
        "-std=c++11",
    ],
    link_style = "static",
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/IOKit.framework",
        "$SDKROOT/System/Library/Frameworks/OpenGL.framework",
        "$SDKROOT/System/Library/Frameworks/Cocoa.framework",
        "$SDKROOT/System/Library/Frameworks/CoreVideo.framework",
    ],
)

apple_bundle(
    name = "bundle-osx",
    binary = ":binary-osx",
    extension = "app",
    info_plist = "Info.plist",
    product_name = "irrlicht-newton-game",
)

cxx_binary(
    name = "binary-generic",
    srcs = [ "main.cpp" ],
    deps = [
        "//vendor/luacppinterface:luacppinterface",
        "//vendor/irrlicht:irrlicht",
        "//vendor/newton-dynamics:newton-dynamics",
    ],
    compiler_flags = [
        "-std=c++11",
    ],
    link_style = "static",
)
